steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['package','-f','./CloudConfigServer']
- name: 'gcr.io/cloud-builders/mvn'
  args: ['package','-f','./WorkerInstance']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/CloudConfigServerImg', './CloudConfigServer' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/WorkerInstanceImg', './WorkerInstance' ]
images:
- 'gcr.io/$PROJECT_ID/CloudConfigServerImg'
- 'gcr.io/$PROJECT_ID/WorkerInstanceImg'